server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/code_confirm
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=always

app.jwt.secret=very-secret-key-change-me
app.jwt.ttl-seconds=3600
app.otp.expiration-job-interval-ms=60000

logging.level.org.example.codeconfirmapp=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO
