email.username=test1@example.com
email.password=test_email_password
email.from=test_email_from@example.com
mail.smtp.host=smtp.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
